[package]
description = "Node Graph Engine for Visual Programming and Data Flow Management"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "cognet"
version = "0.1.0"

[dependencies]
async-trait = "0.1.85"
rayon = "1.10.0"
strum = "0.26.3"
thiserror = "2.0.11"
tokio = {version = "1.43.0", features = ["full"]}
tracing = "0.1.41"
ulid = "1.1.4"
