[package]
description = "Node Graph Engine for Visual Programming and Data Flow Management"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "cognet"
version = "0.1.0"

[lib]
crate-type = ["rlib"]

[target.'cfg(feature = "wasm")'.lib]
crate-type = ["cdylib"]

[dependencies]
async-trait = "0.1.86"
futures = "0.3.31"
inventory = "0.3.19"
strum = "0.26.3"
thiserror = "2.0.11"
tokio = {version = "1.43.0", features = ["full"]}
tracing = "0.1.41"
ulid = "1.1.4"

[features]
wasm = []
