
[tasks.example-wasm]
args = ["make", "--cwd", "crates/wasm", "example-wasm"]
command = "cargo"
description = "Example for wasm"
workspace = false

[tasks.example-add]
description = "Example for add node"
script = [
  "cargo run --example add",
]
workspace = false
