
[tasks.example-wasm]
cwd = "examples/web"
dependencies = ["prepare-wasm"]
description = "Example for wasm"
script = [
  "npx vite",
]
workspace = false

[tasks.prepare-wasm]
args = ["build", "--target", "web", "--out-dir", "../web/pkg"]
command = "wasm-pack"
description = "Example for wasm"
toolchain = "nightly-2024-08-02"
workspace = false
